# Generated by Django 4.2.30 on 2026-04-16 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobee_app', '0002_adminprofile_email_adminprofile_fullname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduateprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='graduateprofile',
            name='fullname',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='graduateprofile',
            name='password',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
