# Generated by Django 4.2.30 on 2026-04-24 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobee_app', '0003_graduateprofile_email_graduateprofile_fullname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='setup',
            field=models.CharField(choices=[('Online (WFH)', 'Online (WFH)'), ('On field (Face-to-face)', 'On field (Face-to-face)'), ('Hybrid', 'Hybrid')], max_length=50),
        ),
    ]
